add_newline = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[✗](bold red) "

[custom.neuron]
command = "neuron query --cached --zettels | jq .[].Path | wc -l"
files = ["neuron.dhall"]
format = " [$output]($style) notes"